/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  carbideSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Carbide Image Registry',
      items: [
        'registry-docs/getting-started',
        {
          type: 'category',
          label: 'Managed Secured Images',
          items: [
            'registry-docs/prereqs',
            {
              type: 'category',
              label: 'Connected Environments',
              items: [
                'registry-docs/validating-images',
                'registry-docs/copying-images',
              ],
            },
            {
              type: 'category',
              label: 'Deploying Into Airgaps',
              items: [
                'registry-docs/downloading-images',
                'registry-docs/validating-airgap-images',
                'registry-docs/loading-images',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Configuration',
          items: [
            'registry-docs/kubernetes-config',
            'registry-docs/rancher-config'
          ],
        },
        'registry-docs/enforcement',
        'registry-docs/architecture'
      ],
    },
    {
      type: 'category',
      label: 'STIGATRON',
      items: [
        'stigatron-docs/introduction',
        'stigatron-docs/getting-started',
        'stigatron-docs/prereqs',
        'stigatron-docs/installation',
        'stigatron-docs/usage'
      ],
    },
    'registry-docs/x2-feedback'
  ],

};

module.exports = sidebars;
